language: objective-c
xcode_workspace: ReactiveWeather.xcworkspace
xcode_scheme: ReactiveWeather
xcode_sdk: 
    - iphonesimulator7.0
    - iphonesimulator7.1
notifications:
    email: false    

# Install the latest version of xctool rather than use Travis default.    
before_install:
    - brew update
    - brew install xctool

# Nothing to install, since dependent Pods are already provided in 
# the repository.
install: true

# Build and run the tests.
script: xctool test -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -sdk $XCODE_SDK