# Travis uses an outdated version of CocoaPods by default.
# We want the latest version, so we have to install it manually.
before_install:
    - gem install cocoapods -v '0.33.1'

# CocoaPods requires the terminal output to be using UTF-8 encoding.
before_script:
  - export LANG=en_US.UTF-8
    
language: objective-c
xcode_workspace: ReactiveWeather.xcworkspace
xcode_scheme: ReactiveWeather
xcode_sdk: 
    - iphonesimulator7.0
    - iphonesimulator7.1
notifications:
    email: false